name: mastodon-rss-bot-docker

on:
  workflow_dispatch:

jobs:
  call-docker-build:
    uses: ./.github/workflows/deploy_ghcr.yaml
    with:
      name: mastodon-rss-bot
      file: Dockerfile
      context: .
